### Create new queue item
POST http://localhost:7040/api/queues
Content-Type: application/json
x-client-aad-roles: ["manager","member"]

{
  "userEmail": "testuser3@example.com"
}

### Get queues 
GET http://localhost:7040/api/queues
Content-Type: application/json
x-client-aad-roles: ["manager","member"]

### Get next user in queue and shift queue
POST http://localhost:7040/api/queues/pop


### Get user queue status
GET http://localhost:7040/api/queues/status/testuser@example.com

### Delete user from queue
DELETE http://localhost:7040/api/queues/testuser@example.com

### Clear entire queue
DELETE http://localhost:7040/api/queues